name: pmu
version: "1.0.0"
config-version: 2

profile: pmu

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  pmu:
    +materialized: view

    staging:
      +schema: staging
      +materialized: view
    
    intermediate:
      +schema: intermediate
      +materialized: view
    
    marts:
      +schema: marts
      +materialized: table