pmu:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'postgres-data') }}"
      port: "{{ env_var('DBT_PORT', '5432') | int }}"
      user: user
      password: password
      dbname: data_db
      schema: analytics
      threads: 4