WITH source AS (
    SELECT
        id,
        source_file,
        file_hash,
        ingested_at,
        json_data,
        substring(lower(source_file) FROM '.*/([0-9]{8})_participant') AS date_str,
        substring(lower(source_file) FROM 'r([0-9]+)')::int AS reunion_num,
        substring(lower(source_file) FROM 'c([0-9]+)')::int AS course_num_ordre
    FROM {{ source('raw', 'raw_participant') }}
),

participants AS (
    SELECT
        id,
        source_file,
        file_hash,
        ingested_at,
        date_str,
        to_date(date_str, 'YYYYMMDD')::text AS course_date,
        to_date(date_str, 'YYYYMMDD')::date AS course_date_dt,
        reunion_num,
        course_num_ordre,
        jsonb_array_elements(json_data -> 'participants') AS participant
    FROM source
)

SELECT
    id AS raw_id,
    source_file,
    file_hash,
    ingested_at,
    course_date_dt AS course_date,
    reunion_num,
    course_num_ordre,
    concat(course_date, '_R', reunion_num, 'C', course_num_ordre) AS course_id_naturel,
    concat(course_date, '_R', reunion_num, 'C', course_num_ordre, '_P', participant ->> 'numPmu') AS participant_course_id_naturel,
    participant ->> 'idCheval' AS participant_id_cheval,
    participant ->> 'nom' AS participant_nom,
    (participant ->> 'numPmu')::int AS participant_num_pmu,
    (participant ->> 'age')::int AS participant_age,
    participant ->> 'sexe' AS participant_sexe,
    participant ->> 'race' AS participant_race,
    participant ->> 'statut' AS participant_statut,
    (participant ->> 'placeCorde')::int AS participant_place_corde,
    participant ->> 'proprietaire' AS participant_proprietaire,
    participant ->> 'entraineur' AS participant_entraineur,
    participant ->> 'driver' AS participant_driver,
    (participant ->> 'driverChange')::boolean AS participant_driver_change,
    participant ->> 'deferre' AS participant_deferre,
    participant ->> 'oeilleres' AS participant_oeilleres,
    participant -> 'robe' ->> 'code' AS participant_robe_code,
    participant -> 'robe' ->> 'libelleCourt' AS participant_robe_libelle_court,
    participant -> 'robe' ->> 'libelleLong' AS participant_robe_libelle_long,
    (participant ->> 'indicateurInedit')::boolean AS participant_indicateur_inedit,
    participant ->> 'musique' AS participant_musique,
    (participant ->> 'nombreCourses')::int AS participant_nombre_courses,
    (participant ->> 'nombreVictoires')::int AS participant_nombre_victoires,
    (participant ->> 'nombrePlaces')::int AS participant_nombre_places,
    (participant ->> 'nombrePlacesSecond')::int AS participant_nombre_places_second,
    (participant ->> 'nombrePlacesTroisieme')::int AS participant_nombre_places_troisieme,
    participant ->> 'nomPere' AS participant_nom_pere,
    participant ->> 'nomMere' AS participant_nom_mere,
    participant ->> 'nomPereMere' AS participant_nom_pere_mere,
    (participant ->> 'ordreArrivee')::int AS participant_ordre_arrivee,
    (participant ->> 'jumentPleine')::boolean AS participant_jument_pleine,
    (participant ->> 'engagement')::boolean AS participant_engagement,
    (participant ->> 'supplement')::numeric AS participant_supplement,
    (participant ->> 'handicapPoids')::numeric AS participant_handicap_poids,
    (participant ->> 'poidsConditionMonte')::numeric AS participant_poids_condition_monte,
    (participant ->> 'poidsConditionMonteChange')::boolean AS participant_poids_condition_monte_change,
    participant ->> 'allure' as participant_allure,
    (participant -> 'gainsParticipant' ->> 'gainsCarriere')::bigint AS participant_gains_carriere,
    (participant -> 'gainsParticipant' ->> 'gainsVictoires')::bigint AS participant_gains_victoires,
    (participant -> 'gainsParticipant' ->> 'gainsPlace')::bigint AS participant_gains_place,
    (participant -> 'gainsParticipant' ->> 'gainsAnneeEnCours')::bigint AS participant_gains_annee_en_cours,
    (participant -> 'gainsParticipant' ->> 'gainsAnneePrecedente')::bigint AS participant_gains_annee_precedente,
    (participant -> 'dernierRapportDirect' ->> 'rapport')::numeric AS participant_cote_directe,
    (participant -> 'dernierRapportReference' ->> 'rapport')::numeric AS participant_cote_reference,
    (participant -> 'dernierRapportDirect' ->> 'favoris')::boolean AS participant_est_favori,
    participant AS participant_json

FROM participants